name: cicd

on:
  push:
    branches: [homolog]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_HUB_LOGIN}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: build docker image
        run: docker build -t davi150205/restaurant_system .
      - name: Push image to Docker Hub
        run: docker push davi150205/restaurant_system:latest

  deploy:
    needs: build
    runs-on: [restaurant-system-ec2]
    steps:
      - name: pull image from docker hub
        run: docker pull davi150205/restaurant_system:latest
      - name: Delete old container
        run: docker rm -f restaurant_system_container
      - name: Run docker container
        run: docker run -d -p 8000:8000 --name restaurant_system_container davi150205/restaurant_system
