CREATE TABLE IF NOT EXISTS `order` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `uuid` char(36) DEFAULT (uuid()),
    `user_id` bigint DEFAULT NULL,
    `address_id` bigint DEFAULT NULL,
    `waiting_time` time NOT NULL,
    `status` tinyint NOT NULL,
    `payment_status` tinyint NOT NULL,
    `payment_date` timestamp NULL DEFAULT NULL,
    `observation` text,
    `delivery_fee` decimal(10,2) DEFAULT NULL,
    `total_price` decimal(10,2) NOT NULL,
    `is_confirmed` tinyint(1) DEFAULT '0',
    `payment_method` tinyint NOT NULL,
    `delivery_type` tinyint NOT NULL,
    `change_for` decimal(10,2) DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `fk_order_user` (`user_id`),
    KEY `fk_order_address` (`address_id`),
    CONSTRAINT `fk_order_address` FOREIGN KEY (`address_id`) REFERENCES `address` (`id`),
    CONSTRAINT `fk_order_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
